SET SERVEROUTPUT ON;

DROP TABLE employees CASCADE CONSTRAINTS;
DROP TABLE departments CASCADE CONSTRAINTS;


CREATE TABLE departments (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) NOT NULL
);

CREATE TABLE employees (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) NOT NULL,
    age NUMBER,
    department_id NUMBER,
    status VARCHAR2(20),
    CONSTRAINT fk_department
        FOREIGN KEY (department_id)
        REFERENCES departments(id)
);


INSERT INTO departments (name) VALUES ('Sales');
INSERT INTO departments (name) VALUES ('Engineering');
INSERT INTO departments (name) VALUES ('HR');

INSERT INTO employees (name, age, department_id, status) VALUES ('Alice', 28, 1, 'Active');
INSERT INTO employees (name, age, department_id, status) VALUES ('Bob', 35, 2, 'Active');
INSERT INTO employees (name, age, department_id, status) VALUES ('Charlie', 40, 3, 'Inactive');
INSERT INTO employees (name, age, department_id, status) VALUES ('David', 32, 1, 'Active');
INSERT INTO employees (name, age, department_id, status) VALUES ('Eve', 27, 2, 'Active');

COMMIT;

-- Тест 1: SELECT — простой пример
DECLARE
    TYPE emp_rec IS RECORD (
        id employees.id%TYPE,
        name employees.name%TYPE,
        age employees.age%TYPE,
        department departments.name%TYPE
    );
    l_cursor SYS_REFCURSOR;
    l_emp emp_rec;
BEGIN
    l_cursor := execute_select('{
        "type": "SELECT",
        "columns": ["employees.id", "employees.name", "employees.age", "departments.name AS department"],
        "tables": ["employees"],
        "joins": [{
            "type": "INNER",
            "table": "departments",
            "on": "employees.department_id = departments.id"
        }]
    }');
    LOOP
        FETCH l_cursor INTO l_emp.id, l_emp.name, l_emp.age, l_emp.department;
        EXIT WHEN l_cursor%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE('--------------------------------');
        DBMS_OUTPUT.PUT_LINE('ID: ' || l_emp.id || ', Name: ' || l_emp.name || ', Age: ' || l_emp.age || ', Department: ' || l_emp.department);
    END LOOP;
    CLOSE l_cursor;
END;
/
    
-- Тест 2: SELECT с условием WHERE и BETWEEN
DECLARE
    TYPE emp_sel2 IS RECORD (
        name employees.name%TYPE,
        age  employees.age%TYPE
    );
    l_cursor  SYS_REFCURSOR;
    l_emp     emp_sel2;
BEGIN
    l_cursor := execute_select('{
        "type": "SELECT",
        "columns": ["name", "age"],
        "tables": ["employees"],
        "conditions": "age BETWEEN 25 AND 35"
    }');
    LOOP
        FETCH l_cursor INTO l_emp.name, l_emp.age;
        EXIT WHEN l_cursor%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE('--------------------------------');
        DBMS_OUTPUT.PUT_LINE('Name: ' || l_emp.name || ', Age: ' || l_emp.age);
    END LOOP;
    CLOSE l_cursor;
END;
/

-- Тест 3: SELECT с GROUP BY и HAVING
DECLARE
    TYPE dept_rec IS RECORD (
        department      departments.name%TYPE,
        employee_count  NUMBER
    );
    l_cursor  SYS_REFCURSOR;
    l_dept    dept_rec;
BEGIN
    l_cursor := execute_select('{
        "type": "SELECT",
        "columns": ["departments.name AS department", "COUNT(employees.id) AS employee_count"],
        "tables": ["departments"],
        "joins": [{
            "type": "LEFT",
            "table": "employees",
            "on": "employees.department_id = departments.id"
        }],
        "group_by": ["departments.name"],
        "having": "COUNT(employees.id) > 1"
    }');
    LOOP
        FETCH l_cursor INTO l_dept.department, l_dept.employee_count;
        EXIT WHEN l_cursor%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE('--------------------------------');
        DBMS_OUTPUT.PUT_LINE('Department: ' || l_dept.department || ', Employee Count: ' || l_dept.employee_count);
    END LOOP;
    CLOSE l_cursor;
END;
/

-- Тест 4: SELECT с JOIN и условием
DECLARE
    TYPE join_rec IS RECORD (
        name       employees.name%TYPE,
        department departments.name%TYPE
    );
    l_cursor SYS_REFCURSOR;
    l_emp    join_rec;
BEGIN
    l_cursor := execute_select('{
        "type": "SELECT",
        "columns": ["employees.name", "departments.name AS department"],
        "tables": ["employees"],
        "joins": [{
            "type": "LEFT",
            "table": "departments",
            "on": "employees.department_id = departments.id"
        }],
        "conditions": "departments.name = ''Sales'' OR departments.name = ''HR''"
    }');
    LOOP
        FETCH l_cursor INTO l_emp.name, l_emp.department;
        EXIT WHEN l_cursor%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE('--------------------------------');
        DBMS_OUTPUT.PUT_LINE('Name: ' || l_emp.name || ', Department: ' || l_emp.department);
    END LOOP;
    CLOSE l_cursor;
END;
/

-- Тест 5: SELECT с вложенным запросом используя IN
DECLARE
    TYPE emp_sel5 IS RECORD (
        id employees.id%TYPE,
        name employees.name%TYPE,
        age employees.age%TYPE,
        department_id employees.department_id%TYPE
    );
    l_cursor SYS_REFCURSOR;
    l_emp emp_sel5;
BEGIN
    l_cursor := execute_select('{
        "type": "SELECT",
        "columns": ["id", "name", "age", "department_id"],
        "tables": ["employees"],
        "conditions": "department_id",
        "nested_operator": "IN",
        "nested": {
            "columns": ["id"],
            "tables": ["departments"],
            "conditions": "name = ''Sales''"
        }
    }');
    LOOP
        FETCH l_cursor INTO l_emp.id, l_emp.name, l_emp.age, l_emp.department_id;
        EXIT WHEN l_cursor%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE('--------------------------------');
        DBMS_OUTPUT.PUT_LINE('ID: ' || l_emp.id || ', Name: ' || l_emp.name || ', Age: ' || l_emp.age || ', Dept ID: ' || l_emp.department_id);
    END LOOP;
    CLOSE l_cursor;
END;
/

-- Тест 6: SELECT с вложенным запросом используя NOT IN
DECLARE
    TYPE emp_sel6 IS RECORD (
        id employees.id%TYPE,
        name employees.name%TYPE,
        age employees.age%TYPE,
        department_id employees.department_id%TYPE
    );
    l_cursor SYS_REFCURSOR;
    l_emp emp_sel6;
BEGIN
    l_cursor := execute_select('{
        "type": "SELECT",
        "columns": ["id", "name", "age", "department_id"],
        "tables": ["employees"],
        "conditions": "department_id",
        "nested_operator": "NOT IN",
        "nested": {
            "columns": ["id"],
            "tables": ["departments"],
            "conditions": "name = ''HR''"
        }
    }');
    LOOP
        FETCH l_cursor INTO l_emp.id, l_emp.name, l_emp.age, l_emp.department_id;
        EXIT WHEN l_cursor%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE('--------------------------------');
        DBMS_OUTPUT.PUT_LINE('ID: ' || l_emp.id || ', Name: ' || l_emp.name || ', Age: ' || l_emp.age || ', Dept ID: ' || l_emp.department_id);
    END LOOP;
    CLOSE l_cursor;
END;
/

-- Тест 7: SELECT с вложенным запросом используя EXISTS
DECLARE
    TYPE emp_sel7 IS RECORD (
        id employees.id%TYPE,
        name employees.name%TYPE
    );
    l_cursor SYS_REFCURSOR;
    l_emp emp_sel7;
BEGIN
    -- columns 1 чтобы взять все столбцы сразу
    l_cursor := execute_select('{
         "type": "SELECT",
         "columns": ["id", "name"],
         "tables": ["employees"],
         "conditions": "",
         "nested_operator": "EXISTS",
         "nested": {
             "columns": ["1"],
             "tables": ["departments"],
             "conditions": "name = ''Engineering''"
         }
    }');
    LOOP
         FETCH l_cursor INTO l_emp.id, l_emp.name;
         EXIT WHEN l_cursor%NOTFOUND;
         DBMS_OUTPUT.PUT_LINE('--------------------------------');
         DBMS_OUTPUT.PUT_LINE('ID: ' || l_emp.id || ', Name: ' || l_emp.name);
    END LOOP;
    CLOSE l_cursor;
END;
/

-- Тест 8: SELECT с вложенным запросом используя NOT EXISTS
DECLARE
    TYPE emp_sel8 IS RECORD (
        id employees.id%TYPE,
        name employees.name%TYPE
    );
    l_cursor SYS_REFCURSOR;
    l_emp emp_sel8;
BEGIN
    l_cursor := execute_select('{
         "type": "SELECT",
         "columns": ["id", "name"],
         "tables": ["employees"],
         "conditions": "",
         "nested_operator": "NOT EXISTS",
         "nested": {
             "columns": ["1"],
             "tables": ["departments"],
             "conditions": "name = ''NonExistingDept''"
         }
    }');
    LOOP
         FETCH l_cursor INTO l_emp.id, l_emp.name;
         EXIT WHEN l_cursor%NOTFOUND;
         DBMS_OUTPUT.PUT_LINE('--------------------------------');
         DBMS_OUTPUT.PUT_LINE('ID: ' || l_emp.id || ', Name: ' || l_emp.name);
    END LOOP;
    CLOSE l_cursor;
END;
/