SET SERVEROUTPUT ON;

DROP TABLE employees CASCADE CONSTRAINTS
DROP TABLE departments CASCADE CONSTRAINTS


CREATE TABLE departments (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) NOT NULL
);

CREATE TABLE employees (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) NOT NULL,
    age NUMBER,
    department_id NUMBER,
    status VARCHAR2(20),
    CONSTRAINT fk_department
        FOREIGN KEY (department_id)
        REFERENCES departments(id)
);


INSERT INTO departments (name) VALUES ('Sales');
INSERT INTO departments (name) VALUES ('Engineering');
INSERT INTO departments (name) VALUES ('HR');

INSERT INTO employees (name, age, department_id, status) VALUES ('Alice', 28, 1, 'Active');
INSERT INTO employees (name, age, department_id, status) VALUES ('Bob', 35, 2, 'Active');
INSERT INTO employees (name, age, department_id, status) VALUES ('Charlie', 40, 3, 'Inactive');

COMMIT;

-- Тест 1: INSERT — простой пример
DECLARE
    l_cursor SYS_REFCURSOR;
    l_message VARCHAR2(4000);
BEGIN
    l_cursor := execute_dml('{
        "type": "INSERT",
        "table": "employees",
        "columns": ["name", "age", "department_id", "status"],
        "values": ["''John Doe''", "30", "1", "''Active''"]
    }');
    FETCH l_cursor INTO l_message;
    DBMS_OUTPUT.PUT_LINE('Test INSERT (simple): ' || l_message);
    CLOSE l_cursor;

    FOR rec IN (SELECT id, name, age, department_id, status FROM employees ORDER BY id) LOOP
        DBMS_OUTPUT.PUT_LINE('ID: ' || rec.id || ', Name: ' || rec.name || ', Age: ' || rec.age || ', Department ID: ' || rec.department_id || ', Status: ' || rec.status);
    END LOOP;
END;
/

-- Тест 2: INSERT — с подзапросом
DECLARE
    l_cursor SYS_REFCURSOR;
    l_message VARCHAR2(4000);
BEGIN
    l_cursor := execute_dml('{
        "type": "INSERT",
        "table": "employees",
        "columns": ["name", "age", "department_id", "status"],
        "values": ["''Jane Smith''", "25", "(SELECT id FROM departments WHERE name = ''Engineering'')", "''Active''"]
    }');
    FETCH l_cursor INTO l_message;
    DBMS_OUTPUT.PUT_LINE('Test INSERT (with subquery): ' || l_message);
    CLOSE l_cursor;

    FOR rec IN (SELECT id, name, age, department_id, status FROM employees ORDER BY id) LOOP
        DBMS_OUTPUT.PUT_LINE('ID: ' || rec.id || ', Name: ' || rec.name || ', Age: ' || rec.age || ', Department ID: ' || rec.department_id || ', Status: ' || rec.status);
    END LOOP;
END;
/

-- Тест 3: UPDATE — простой пример
DECLARE
    l_cursor SYS_REFCURSOR;
    l_message VARCHAR2(4000);
BEGIN
    l_cursor := execute_dml('{
        "type": "UPDATE",
        "table": "employees",
        "set": "age = 31",
        "conditions": "name = ''Alice''"
    }');
    FETCH l_cursor INTO l_message;
    DBMS_OUTPUT.PUT_LINE('Test UPDATE (simple): ' || l_message);
    CLOSE l_cursor;

    FOR rec IN (SELECT id, name, age, department_id, status FROM employees ORDER BY id) LOOP
        DBMS_OUTPUT.PUT_LINE('ID: ' || rec.id || ', Name: ' || rec.name || ', Age: ' || rec.age || ', Department ID: ' || rec.department_id || ', Status: ' || rec.status);
    END LOOP;
END;
/

-- Тест 4: UPDATE — с подзапросом
DECLARE
    l_cursor SYS_REFCURSOR;
    l_message VARCHAR2(4000);
BEGIN
    l_cursor := execute_dml('{
        "type": "UPDATE",
        "table": "employees",
        "set": "status = ''Promoted''",
        "conditions": "department_id IN (SELECT id FROM departments WHERE name = ''Engineering'')"
    }');
    FETCH l_cursor INTO l_message;
    DBMS_OUTPUT.PUT_LINE('Test UPDATE (with subquery): ' || l_message);
    CLOSE l_cursor;

    FOR rec IN (SELECT id, name, age, department_id, status FROM employees ORDER BY id) LOOP
        DBMS_OUTPUT.PUT_LINE('ID: ' || rec.id || ', Name: ' || rec.name || ', Age: ' || rec.age || ', Department ID: ' || rec.department_id || ', Status: ' || rec.status);
    END LOOP;
END;
/

-- Тест 5: DELETE — простой пример
DECLARE
    l_cursor SYS_REFCURSOR;
    l_message VARCHAR2(4000);
BEGIN
    l_cursor := execute_dml('{
        "type": "DELETE",
        "table": "employees",
        "conditions": "name = ''Charlie''"
    }');
    FETCH l_cursor INTO l_message;
    DBMS_OUTPUT.PUT_LINE('Test DELETE (simple): ' || l_message);
    CLOSE l_cursor;

    FOR rec IN (SELECT id, name, age, department_id, status FROM employees ORDER BY id) LOOP
        DBMS_OUTPUT.PUT_LINE('ID: ' || rec.id || ', Name: ' || rec.name || ', Age: ' || rec.age || ', Department ID: ' || rec.department_id || ', Status: ' || rec.status);
    END LOOP;
END;
/

-- Тест 6: DELETE — с подзапросом
DECLARE
    l_cursor SYS_REFCURSOR;
    l_message VARCHAR2(4000);
BEGIN
    l_cursor := execute_dml('{
        "type": "DELETE",
        "table": "employees",
        "conditions": "department_id IN (SELECT id FROM departments WHERE name = ''HR'')"
    }');
    FETCH l_cursor INTO l_message;
    DBMS_OUTPUT.PUT_LINE('Test DELETE (with subquery): ' || l_message);
    CLOSE l_cursor;

    FOR rec IN (SELECT id, name, age, department_id, status FROM employees ORDER BY id) LOOP
        DBMS_OUTPUT.PUT_LINE('ID: ' || rec.id || ', Name: ' || rec.name || ', Age: ' || rec.age || ', Department ID: ' || rec.department_id || ', Status: ' || rec.status);
    END LOOP;
END;
/

-- Тест 7: INSERT — с вложенным запросом через nested
DECLARE
    l_cursor SYS_REFCURSOR;
    l_message VARCHAR2(4000);
BEGIN
    l_cursor := execute_dml('{
        "type": "INSERT",
        "table": "employees",
        "columns": ["name", "age", "department_id", "status"],
        "values": ["''Mark Twain''", "55", "SUBQUERY", "''Active''"],
        "nested": {
            "columns": ["id"],
            "tables": ["departments"],
            "conditions": "name = ''HR''"
        }
    }');
    FETCH l_cursor INTO l_message;
    DBMS_OUTPUT.PUT_LINE('Test INSERT (with nested subquery): ' || l_message);
    CLOSE l_cursor;

    FOR rec IN (SELECT id, name, age, department_id, status FROM employees ORDER BY id) LOOP
        DBMS_OUTPUT.PUT_LINE('ID: ' || rec.id || ', Name: ' || rec.name || ', Age: ' || rec.age || ', Department ID: ' || rec.department_id || ', Status: ' || rec.status);
    END LOOP;
END;
/