-- Create table to store report data
CREATE TABLE report_log (
    report_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    creation_date DATE,
    report_content CLOB
);

CREATE OR REPLACE PROCEDURE generate_audit_report (
    p_start_date   IN DATE DEFAULT NULL
) IS
    v_dept_insert   NUMBER;
    v_dept_update   NUMBER;
    v_dept_delete   NUMBER;
    
    v_emp_insert    NUMBER;
    v_emp_update    NUMBER;
    v_emp_delete    NUMBER;
    
    v_sal_insert    NUMBER;
    v_sal_update    NUMBER;
    v_sal_delete    NUMBER;
    
    v_html          CLOB;
    v_start_date    DATE;
BEGIN
    IF p_start_date IS NOT NULL THEN
        v_start_date := p_start_date;
    ELSE
        SELECT creation_date INTO v_start_date
        FROM report_log
        ORDER BY creation_date DESC
        FETCH FIRST 1 ROW ONLY;
    END IF;
    
    v_html := '<html><head><meta charset="UTF-8"><title>Отчет изменений</title></head><body>';
    v_html := v_html || '<h2>Отчет изменений с ' || TO_CHAR(v_start_date, 'DD.MM.YYYY HH24:MI:SS') || '</h2>';
    
    SELECT NVL(MAX(CASE WHEN operation_type = 'INSERT' THEN cnt END), 0),
           NVL(MAX(CASE WHEN operation_type = 'UPDATE' THEN cnt END), 0),
           NVL(MAX(CASE WHEN operation_type = 'DELETE' THEN cnt END), 0)
      INTO v_dept_insert, v_dept_update, v_dept_delete
      FROM (
            SELECT operation_type, COUNT(*) cnt
            FROM departments_audit
            WHERE operation_date >= v_start_date
            GROUP BY operation_type
           );
    
    SELECT NVL(MAX(CASE WHEN operation_type = 'INSERT' THEN cnt END), 0),
           NVL(MAX(CASE WHEN operation_type = 'UPDATE' THEN cnt END), 0),
           NVL(MAX(CASE WHEN operation_type = 'DELETE' THEN cnt END), 0)
      INTO v_emp_insert, v_emp_update, v_emp_delete
      FROM (
            SELECT operation_type, COUNT(*) cnt
            FROM employees_audit
            WHERE operation_date >= v_start_date
            GROUP BY operation_type
           );
    
    SELECT NVL(MAX(CASE WHEN operation_type = 'INSERT' THEN cnt END), 0),
           NVL(MAX(CASE WHEN operation_type = 'UPDATE' THEN cnt END), 0),
           NVL(MAX(CASE WHEN operation_type = 'DELETE' THEN cnt END), 0)
      INTO v_sal_insert, v_sal_update, v_sal_delete
      FROM (
            SELECT operation_type, COUNT(*) cnt
            FROM salary_history_audit
            WHERE operation_date >= v_start_date
            GROUP BY operation_type
           );
    v_html := v_html || '<h1>DEPARTMENTS:</h1><p>insert-' || v_dept_insert || ', update-' || v_dept_update || ', delete-' || v_dept_delete;
    v_html := v_html || '<h1>EMPLOYEES:</h1><p>insert-' || v_emp_insert || ', update-' || v_emp_update || ', delete-' || v_emp_delete;
    v_html := v_html || '<h1>SALARY_HISTORY:</h1><p>insert-' || v_sal_insert || ', update-' || v_sal_update || ', delete-' || v_sal_delete;
    v_html := v_html || '</body></html>';
    
    INSERT INTO report_log (creation_date, report_content)
    VALUES (SYSDATE, v_html);

EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Ошибка: ' || SQLERRM);
        ROLLBACK;
END generate_audit_report;
/