CREATE TABLE GROUPS (
    ID NUMBER,
    NAME VARCHAR2(100),
    C_VAL NUMBER
);
CREATE TABLE STUDENTS (
    ID NUMBER,
    NAME VARCHAR2(100),
    GROUPS_ID NUMBER
);


DROP TABLE STUDENTS;
DROP TABLE GROUPS;


SELECT * FROM GROUPS;
DELETE FROM GROUPS;

SELECT * FROM STUDENTS;
DELETE FROM STUDENTS;