CREATE SEQUENCE log_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE STUDENT_LOG (
    LOG_ID NUMBER,
    STUDENT_ID  NUMBER,
    ACTION_TYPE VARCHAR2(10),
    OLD_GROUP NUMBER,
    NEW_GROUP NUMBER,
    OLD_NAME VARCHAR2(100),
    NEW_NAME VARCHAR2(100),
    CHANGE_DATE TIMESTAMP DEFAULT SYSTIMESTAMP
);

DROP TABLE STUDENT_LOG;

CREATE OR REPLACE TRIGGER log_student_changes
BEFORE INSERT OR UPDATE OR DELETE ON STUDENTS
FOR EACH ROW
BEGIN
    IF INSERTING THEN 
            INSERT INTO STUDENT_LOG (LOG_ID, STUDENT_ID, ACTION_TYPE, OLD_GROUP, NEW_GROUP, OLD_NAME, NEW_NAME)
            VALUES (log_seq.NEXTVAL, :NEW.ID, 'INSERT', NULL, :NEW.GROUPS_ID, NULL, :NEW.NAME);
    ELSIF UPDATING THEN
            INSERT INTO STUDENT_LOG (LOG_ID, STUDENT_ID, ACTION_TYPE, OLD_GROUP, NEW_GROUP, OLD_NAME, NEW_NAME)
            VALUES (log_seq.NEXTVAL, :OLD.ID, 'UPDATE', :OLD.GROUPS_ID, :NEW.GROUPS_ID, :OLD.NAME, :NEW.NAME);
    ELSIF DELETING THEN
            INSERT INTO STUDENT_LOG (LOG_ID, STUDENT_ID, ACTION_TYPE, OLD_GROUP, NEW_GROUP, OLD_NAME, NEW_NAME)
            VALUES (log_seq.NEXTVAL, :OLD.ID, 'DELETE', :OLD.GROUPS_ID, NULL, :OLD.NAME, NULL);
    END IF;
END;


-- TEST
BEGIN 
    INSERT INTO GROUPS (ID, NAME, C_VAL) VALUES (1, 'GROUP A', 0);
    INSERT INTO STUDENTS (ID, NAME, GROUPS_ID) VALUES (1, 'ST 1', 1);
    UPDATE STUDENTS SET NAME = 'St 1 Updated' WHERE ID = 1;
    DELETE FROM STUDENTS WHERE ID = 1;

    DBMS_OUTPUT.PUT_LINE('----- Логи после вставки нового студента: ');
    FOR rec IN (SELECT * FROM STUDENT_LOG) LOOP
        DBMS_OUTPUT.PUT_LINE('ID: ' || rec.LOG_ID || 
                            ', Student: ' || rec.STUDENT_ID || 
                            ', Action: ' || rec.ACTION_TYPE || 
                            ', Old Group: ' || rec.OLD_GROUP || 
                            ', New Group: ' || rec.NEW_GROUP || 
                            ', Old Name: ' || rec.OLD_NAME || 
                            ', New Name: ' || rec.NEW_NAME ||
                            ', Datetime: ' || TO_CHAR(rec.CHANGE_DATE, 'DD-MON-YYYY HH24:MI:SS'));
    END LOOP;
    ROLLBACK;
END;

SELECT * FROM STUDENTS;
SELECT * FROM STUDENT_LOG;

DELETE FROM GROUPS;
DELETE FROM STUDENT_LOG;